name: dart_package
description: An example Dart package created with very_good_cli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
