name: Dart Pub Publish Workflow

on:
  workflow_call:
    inputs:
      flutter_channel:
        required: false
        type: string
        default: "stable"
      flutter_version:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      timeout_minutes:
        required: false
        type: number
        default: 5
    # Deprecated, will be used if passed in but using the "Setup Dart" action is recommended
    secrets:
      pub_credentials:
        required: true

jobs:
  publish:
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}

    timeout-minutes: ${{inputs.timeout_minutes}}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2.23.0.23.0
        with:
          flutter-version: ${{inputs.flutter_version}}
          channel: ${{inputs.flutter_channel}}
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🔐 Setup Pub Credentials\
        if: ${{ secrets.pub_credentials != '' }}
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          echo '${{secrets.pub_credentials}}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

      - name: 🎯 Setup Dart
        if: ${{ secrets.pub_credentials == '' }}
        uses: dart-lang/setup-dart@v1.7.2
        with:
          sdk: ${{inputs.dart_sdk}}

      - name: 🌵 Dry Run
        run: flutter pub publish --dry-run

      - name: 📢 Publish
        run: flutter pub publish -f
