name: Verify Dart Package Workflow

on:
  pull_request:
    paths:
      - "examples/dart_package/**"
      - ".github/workflows/dart_package.yml"
      - ".github/workflows/verify_dart_package.yml"

jobs:
  build:
    uses: .github/workflows/dart_package.yml@$GITHUB_REF
    with:
      working_directory: examples/dart_package